/* Generated by MyraPad at 26.03.2024 16:25:42 */

using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
using Myra.Graphics2D;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI;

namespace Techardry.UI
{
	partial class IngameUi: Panel
	{
		private void BuildUI()
		{
			var panel1 = new Panel();
			panel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			panel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			panel1.Width = 50;
			panel1.Height = 5;
			panel1.Background = new SolidBrush("#000000C8");

			var panel2 = new Panel();
			panel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			panel2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			panel2.Width = 5;
			panel2.Height = 50;
			panel2.Background = new SolidBrush("#000000C8");

			Pos = new Label();
			Pos.Text = "Position: ";
			Pos.Id = "Pos";

			LookingAt = new Label();
			LookingAt.Text = "Looking at: 10.55, 10.55, 10.55";
			LookingAt.Id = "LookingAt";

			BuildSize = new Label();
			BuildSize.Text = "Building Size:  ";
			BuildSize.Id = "BuildSize";

			Fps = new Label();
			Fps.Text = "FPS: ";
			Fps.Id = "Fps";

			CurrentBlockView = new Label();
			CurrentBlockView.Text = "Current Block (View): ";
			CurrentBlockView.Id = "CurrentBlockView";

			CurrentBlockHolding = new Label();
			CurrentBlockHolding.Text = "Current Block (Holding):";
			CurrentBlockHolding.Id = "CurrentBlockHolding";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			verticalStackPanel1.MinWidth = 275;
			verticalStackPanel1.Margin = new Thickness(5);
			verticalStackPanel1.Border = new SolidBrush("#101010FF");
			verticalStackPanel1.BorderThickness = new Thickness(2);
			verticalStackPanel1.Background = new SolidBrush("#202020C8");
			verticalStackPanel1.Widgets.Add(Pos);
			verticalStackPanel1.Widgets.Add(LookingAt);
			verticalStackPanel1.Widgets.Add(BuildSize);
			verticalStackPanel1.Widgets.Add(Fps);
			verticalStackPanel1.Widgets.Add(CurrentBlockView);
			verticalStackPanel1.Widgets.Add(CurrentBlockHolding);

			
			Widgets.Add(panel1);
			Widgets.Add(panel2);
			Widgets.Add(verticalStackPanel1);
		}

		
		public Label Pos;
		public Label LookingAt;
		public Label BuildSize;
		public Label Fps;
		public Label CurrentBlockView;
		public Label CurrentBlockHolding;
	}
}
