/* Generated by MyraPad at 26.03.2024 16:25:42 */

using System.Numerics;
using MintyCore.Modding;
using MintyCore.Utils;

namespace Techardry.UI
{
	public partial class IngameUi
	{
		private IModManager ModManager { get; }
		
		public IngameUi(IModManager modManager)
		{
			ModManager = modManager;
			BuildUI();
		}
		
		public void SetBlockPos(Vector3 pos)
		{
			LookingAt.Text = $"Looking at: {pos.X:F2}, {pos.Y:F2}, {pos.Z:F2}";
		}
		
		public void SetPlayerPos(Vector3 pos)
		{
			Pos.Text = $"Player Pos: {pos.X:F2}, {pos.Y:F2}, {pos.Z:F2}";
		}
		
		public void SetBlockSize(double size)
		{
			BuildSize.Text = $"Block Size: {size:F2}m";
		}
		
		public void SetFps(int fps)
		{
			Fps.Text = $"FPS: {fps}";
		}
		
		public void SetCurrentBlockView(Identification block)
		{
			CurrentBlockView.Text = $"Current Block (View): {ModManager.RegistryManager.GetObjectStringId(block.Mod, block.Category, block.Object)}";
		}
		
		public void SetCurrentBlockHolding(Identification block)
		{
			CurrentBlockHolding.Text = $"Current Block (Holding): {ModManager.RegistryManager.GetObjectStringId(block.Mod, block.Category, block.Object)}";
		}
	}
}